apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: switching-db-maintenance-secrets
  namespace: switching
spec:
  refreshInterval: 1h
  secretStoreRef: {name: switching-vault, kind: SecretStore}
  target:
    name: switching-db-maintenance-secrets
    creationPolicy: Owner
  data:
    - {secretKey: DB_HOST, remoteRef: {key: switching/production/database-maintenance, property: host}}
    - {secretKey: DB_PORT, remoteRef: {key: switching/production/database-maintenance, property: port}}
    - {secretKey: DB_NAME, remoteRef: {key: switching/production/database-maintenance, property: database}}
    - {secretKey: DB_MAINTENANCE_USERNAME, remoteRef: {key: switching/production/database-maintenance, property: username}}
    - {secretKey: DB_MAINTENANCE_PASSWORD, remoteRef: {key: switching/production/database-maintenance, property: password}}
