apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: switching-application-secrets
  namespace: switching
  labels:
    app.kubernetes.io/name: switching-api
    app.kubernetes.io/component: application
spec:
  refreshPolicy: Periodic
  refreshInterval: 5m
  secretStoreRef:
    name: switching-vault
    kind: SecretStore
  target:
    name: switching-secrets
    creationPolicy: Orphan
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: switching-api
          app.kubernetes.io/managed-by: external-secrets
  data:
    - secretKey: DB_URL
      remoteRef: { key: switching/prod/application, property: DB_URL }
    - secretKey: DB_USERNAME
      remoteRef: { key: switching/prod/application, property: DB_USERNAME }
    - secretKey: DB_PASSWORD
      remoteRef: { key: switching/prod/application, property: DB_PASSWORD }
    - secretKey: MESSAGE_CRYPTO_KEY_BASE64
      remoteRef: { key: switching/prod/application, property: MESSAGE_CRYPTO_KEY_BASE64 }
    - secretKey: OAUTH_JWT_SECRET
      remoteRef: { key: switching/prod/application, property: OAUTH_JWT_SECRET }
    - secretKey: SMOS_JWT_SECRET
      remoteRef: { key: switching/prod/application, property: SMOS_JWT_SECRET }
    - secretKey: KAFKA_SASL_JAAS_CONFIG
      remoteRef: { key: switching/prod/application, property: KAFKA_SASL_JAAS_CONFIG }
    - secretKey: KAFKA_SSL_TRUSTSTORE_PASSWORD
      remoteRef: { key: switching/prod/application, property: KAFKA_SSL_TRUSTSTORE_PASSWORD }
    - secretKey: KAFKA_SSL_KEYSTORE_PASSWORD
      remoteRef: { key: switching/prod/application, property: KAFKA_SSL_KEYSTORE_PASSWORD }
    - secretKey: BOL_FIU_API_KEY
      remoteRef: { key: switching/prod/application, property: BOL_FIU_API_KEY }
    - secretKey: AML_BOL_SANCTIONS_API_KEY
      remoteRef: { key: switching/prod/application, property: AML_BOL_SANCTIONS_API_KEY }
    - secretKey: ARCHIVE_DB_PASSWORD
      remoteRef: { key: switching/prod/application, property: ARCHIVE_DB_PASSWORD }
    - secretKey: OBJECT_STORAGE_ACCESS_KEY
      remoteRef: { key: switching/prod/application, property: OBJECT_STORAGE_ACCESS_KEY }
    - secretKey: OBJECT_STORAGE_SECRET_KEY
      remoteRef: { key: switching/prod/application, property: OBJECT_STORAGE_SECRET_KEY }
