apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: switching-ops-egress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: switching
      app.kubernetes.io/component: ops-job
  policyTypes: ["Egress"]
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: database
      ports:
        - protocol: TCP
          port: 5432
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 9090
