apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: switching-api
  namespace: switching
spec:
  podSelector:
    matchLabels:
      app: switching-api
  policyTypes: [Egress]
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: switching
      ports:
        - { protocol: TCP, port: 5432 }
        - { protocol: TCP, port: 9092 }
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - { protocol: UDP, port: 53 }
        - { protocol: TCP, port: 53 }
